# Generated by Django 4.0.4 on 2022-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='second',
            field=models.IntegerField(default=0),
        ),
    ]
