# Generated by Django 4.0.4 on 2022-05-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.TextField()),
                ('truetag1', models.CharField(max_length=30, null=True)),
                ('truetag2', models.CharField(max_length=30, null=True)),
                ('truetag3', models.CharField(max_length=30, null=True)),
                ('truetag4', models.CharField(max_length=30, null=True)),
                ('truetag5', models.CharField(max_length=30, null=True)),
                ('falsetag1', models.CharField(max_length=30, null=True)),
                ('falsetag2', models.CharField(max_length=30, null=True)),
                ('falsetag3', models.CharField(max_length=30, null=True)),
                ('falsetag4', models.CharField(max_length=30, null=True)),
                ('falsetag5', models.CharField(max_length=30, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app.user')),
            ],
        ),
    ]
