# Generated by Django 4.0.4 on 2022-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccount', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True),
        ),
    ]
