# Generated by Django 4.0.4 on 2022-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccount', '0004_notice_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='post_date',
            field=models.DateField(),
        ),
    ]
