# Generated by Django 4.0.4 on 2022-05-28 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAccount', '0005_alter_notice_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
