# Generated by Django 4.0.4 on 2022-05-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0002_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='lounge',
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge', models.TextField()),
                ('photos', models.ImageField(upload_to='')),
                ('schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapApp.school')),
            ],
        ),
    ]
