# Generated by Django 4.0.4 on 2022-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0003_remove_info_lounge_lounge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='lounge_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lounge',
            name='lounge',
            field=models.CharField(max_length=20),
        ),
    ]
