# Generated by Django 4.0.4 on 2022-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0004_lounge_lounge_info_alter_lounge_lounge'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
