# Generated by Django 4.0.4 on 2022-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0005_info_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
