# Generated by Django 4.0.4 on 2022-05-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0006_lounge_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapApp.school')),
            ],
        ),
    ]
