# Generated by Django 4.0.4 on 2022-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0007_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
