# Generated by Django 4.0.4 on 2022-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0008_lounge_info_delete_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='info',
        ),
        migrations.AddField(
            model_name='school',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
