# Generated by Django 4.0.4 on 2022-05-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0009_remove_lounge_info_school_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapApp.school')),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapApp.info')),
            ],
        ),
    ]
