# Generated by Django 4.0.4 on 2022-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0010_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='lounge',
            field=models.CharField(max_length=50),
        ),
    ]
