# Generated by Django 4.0.4 on 2022-05-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0011_alter_lounge_lounge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='schools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge', to='MapApp.school'),
        ),
    ]
