# Generated by Django 4.0.4 on 2022-05-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pig_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pig'),
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
