# Generated by Django 4.0.4 on 2022-05-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_schedule_pig_info_delete_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='app.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_late', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_set', to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='pig',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='pig', to='app.participation'),
        ),
    ]
