# Generated by Django 4.0.4 on 2022-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pig_host_participation_pig_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='pig', to='app.participation'),
        ),
    ]
