# Generated by Django 4.0.4 on 2022-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='arrived',
            field=models.ManyToManyField(blank=True, related_name='arrived_set', to='app.participation'),
        ),
    ]
