# Generated by Django 4.0.4 on 2022-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schedule_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrived',
            field=models.ManyToManyField(blank=True, related_name='arrived_set', to='app.profile'),
        ),
    ]
