# Generated by Django 4.0.4 on 2022-05-23 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(to='mainApp.card')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlist', to='mainApp.card')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('invitation_link', models.TextField(null=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to='mainApp.card')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
