# Generated by Django 4.0.4 on 2022-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_friendlists_groups_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='invitation_link',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='invitation_link',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(null=True, to='mainApp.card'),
        ),
    ]
