# Generated by Django 4.0.4 on 2022-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_card_invitation_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(to='mainApp.card'),
        ),
    ]
