# Generated by Django 4.0.4 on 2022-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_groups_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='phone_num',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
