# Generated by Django 4.0.4 on 2022-05-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_friendlists_friends_alter_groups_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlists',
            name='friends',
            field=models.ManyToManyField(related_name='myfriends', to='mainApp.card'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='mygroups', to='mainApp.card'),
        ),
    ]
