# Generated by Django 4.0.4 on 2022-05-24 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0007_alter_friendlists_friends_alter_groups_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlists',
            name='friends',
            field=models.ManyToManyField(related_name='myfriends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='mygroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
