# Generated by Django 4.0.4 on 2022-05-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_card_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='profile_pic',
        ),
    ]
