# Generated by Django 4.0.4 on 2022-05-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_card_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='profile_pic',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
